let cezalar = [
    {isim : "Vjedhje e Bankes*", para : 19000, hapis :900, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Vjedhje e Argjentarise*", para : 12000, hapis :820, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Vjedhje e Shitores*", para : 6800, hapis :550, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Vjedhje e Kontinjerave*", para : 5000, hapis :700, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Vrasje e Policit", para : 30000, hapis :1300, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Vrasje e Qytetarit", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Tentim vrasje e Policit", para : 10000 , hapis :1000, kamu :10, illegal : false, active : false, tceza : 4 },
    {isim : "Tentim vrasje e qytetarit", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Shkaktimi i rrezikut te pergjithshem", para : 57000, hapis :2500, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Terrorizem", para : 87000, hapis :2750, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Vozitje pa patent shofer", para : 2000, hapis :100, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Pengim i personit zyrtar", para : 3500, hapis :400, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Posedim i hapur i armve t gjata", para : 8400, hapis :200, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tejkalim i shpejtsise mbi 90km/h", para : 1700, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Tejkalim i shpejtesise mbi 120 km/h.", para : 3000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Armbajtje pa leje*", para : 8000, hapis :200, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Korrupsion ndaj policis", para : 5000, hapis :500, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Tentim per tjy shmang arrestit (ikje)", para : 5500, hapis :800, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Sjellje e keqe ndaj officerit", para : 1000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Nisje e vrullshme (launch)", para : 1200, hapis :0, kamu :20, illegal : false, active : false, tceza : 1 },
    {isim : "Vozitje e rrezikshme (4+shkelje)", para : 2500, hapis :450, kamu :0, illegal : false, active : false, tceza : 5 },
    {isim : "Vjedhje e drropit me paramendim", para : 22000, hapis :1000, kamu :0, illegal : false, active : false, tceza : 3 },
    {isim : "Plackitje e shtepive private", para : 3500, hapis :1850, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Plackitje e policit", para : 22000, hapis :990, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Posedim i drroges klasi par (weed)", para : 3500, hapis :550, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Shitje,Posedim dhe Kultivim i pa autorizuar i substancave Psikotrope/Analoge", para : 8000, hapis :870, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Posedim i droges klasa 2 (methamorphine, cocaine)*", para : 6000, hapis :600, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Demtim tjeter me dashje", para : 1200, hapis :150, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vjedhje e vetures", para : 4500, hapis :600, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Kidnapim i policit", para : 12000, hapis :1200, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kidnapim i qytetarit", para : 5000, hapis :450, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Trransport me qenie njerzore ", para : 6000, hapis :290, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Keqperdorim i detyres zyrtare", para : 10000, hapis :900, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Marrje e rrushfetit", para : 12000, hapis :1200, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Dhenie e rreme e deklaratave zyrtare", para : 8000, hapis :590, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Sulm ndaj personit zyrtar", para : 9000, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kercenim ndaj personit zyrtar", para : 4000, hapis :300, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Paraqitje e rreme si person zyrtar", para : 5500, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Falsifikim i targave te vetures", para : 12000, hapis :3500, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Posedim i paisjeve te polise", para : 50000, hapis :900, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vjedhje e gjerave materiale", para : 5000, hapis :430, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Vjedhje e vetures se policise", para : 4300, hapis :300, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tentim vjdhje e vetures se policise", para : 2000, hapis :300, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Mashtrrim", para : 3200, hapis :450, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Ngacmim seksual", para : 7500, hapis :1100, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Keqpordorim i bashkpunimit ne besim", para : 5000, hapis :450, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Mospranim i fajesis", para : 4000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Bllokim i qarkullimit ne rruge publike", para : 1200, hapis :200, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Mosrrespektim i urdhrit te personit zyrtar", para : 3500, hapis :450, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Hyrje ne zone te ndaluar me shenje", para : 4000, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vrasje me paramendim", para : 1200, hapis :150, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Arratisje nga ndalimi policor", para : 7000, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tentim per arratisje nga ndalimi", para : 4000, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Pjesmarrje ne veper penale/ndihme", para : 1900, hapis :700, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Rrezistim i arrestimit", para : 12000, hapis :800, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Percarja kombetare", para : 12000, hapis :500, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vrasje e pa qellimshme", para : 8000, hapis :450, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Shkaktim i trrazirave apo protestave", para : 4000, hapis :330, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Okupim i prones private apo publike", para : 3000, hapis :250, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Demtim ne prone", para : 2000, hapis :400, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Stimulim i rastit", para : 1000, hapis :350, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Plackitje e qytetarve", para : 12000, hapis :890, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vetura ne gjendje te rende operimi", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Mjeti operon pa drrita te dukshme", para : 950, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Ofendon qytetarin civil", para : 450, hapis :120, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Keqordorim i aremes", para : 4000, hapis :650, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Renditje e gabuar ne semafor", para : 250, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Parkim ne vend te gabuar", para : 100, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Hyrje ne rrug nje kaheshe", para : 445, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Perdorim i borise pa nevoj", para : 55, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Xhamat e zeza +60%", para : 250, hapis :0, kamu :15, illegal : false, active : false, tceza : 0 },
    {isim : "Gomat e pa peshtatshme", para : 100, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tentim vjedhje te makines", para : 1500, hapis :120, kamu :0, illegal : false, active : false, tceza : 2 },
    {isim : "Refuzim i paraqitjes se mjetit te indetifikimit", para : 1500, hapis :500, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Prishje e rendit dhe qetsise", para : 430, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Shetitje me kafshe pa masa mbrojtse", para : 430, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Perdorim i telefonit gjat vozitjes", para : 300, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Voztje pa rrip te sigurise", para : 250, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vozitje pa helmete mbrojtse", para : 100, hapis :0, kamu :0, illegal : false, active : false, tceza : 3 },
    {isim : "Posedimi i parave te zeza", para : 2500, hapis :480, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Tejkalim i drrites se kuqe ne semafor", para : 1000, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Deshtim per ndalje ne shenje te trrafikut", para : 500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },

]